version: '3.8'

services:
  bixportal:
    container_name: bixportal
    image: ghcr.io/${GITHUB_USER}/bixportal-${CLIENT_ID}:latest
    restart: unless-stopped
    networks:
      - bix-network
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    env_file:
      - .env.production

networks:
  bix-network:
    external: true